version: '3.8'
services:
  scrapper:
    build:
      context: . 
      dockerfile: ./compose/fastapi/Dockerfile
    image: scrapper_fastapi 
    command: /start
    ports:
      - "8010:8000"
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
    volumes: ['./src:/usr/share/src']  
 
  worker:
    build:
      context: . 
      dockerfile: ./compose/fastapi/Dockerfile
    image: scrapper_celery_worker 
    command: /start-celeryworker
    volumes: ['./src:/usr/share/src']  
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis


  monitor:
    build:
      context: . 
      dockerfile: ./compose/fastapi/Dockerfile
    image: scrapper_celery_monitor 
    command: /start-flower
    volumes: ['./src:/usr/share/src']  
    env_file:
      - .env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - worker
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: